substitutions:
  ac_entity_id: climate.actron_test_aircon

esphome:
  name: deinyon-ac-remote-host

packages:
  ui: !include deinyon-ac-remote-ui.yml

host:

api:

display:
  - platform: sdl
    id: my_display
    dimensions:
      width: 450
      height: 600

touchscreen:
  - platform: sdl
    display: my_display
