esphome:
  name: deinyon-climate-host

packages:
  ui: !include deinyon-climate-ui3.yml

host:

display:
  - platform: sdl
    id: my_display
    dimensions:
      width: 450
      height: 600

touchscreen:
  - platform: sdl
    display: my_display
