esphome:
  name: lvgl-test

host:

display:
  - platform: sdl
    id: my_display
    dimensions:
      width: 600
      height: 450

touchscreen:
  - platform: sdl
    display: my_display  

font:
  - file: "gfonts://Roboto@700"
    id: roboto_bold
    size: 24

lvgl:
  displays:
    - my_display
  pages:
    - id: main_page
      widgets:
        - label:
            text: "Hello World"
            align: CENTER
            text_font: roboto_bold
